- name: Add scripts/{{ site_name }} folder
  ansible.builtin.file:
    path: /scripts/{{ site_name }}
    state: directory
    owner: "{{ site_name }}"
    group: "{{ site_name }}"
    mode: '0700'
  become: true

- name: Add templated script deploy.sh
  ansible.builtin.template:
    src: ../files/deploy.sh
    dest: /scripts/{{ site_name }}/deploy.sh
    owner: "{{ site_name }}"
    group: "{{ site_name }}"
    mode: '0500'
  become: true

- name: Add templated script start.sh
  ansible.builtin.template:
    src: ../files/start.sh
    dest: /scripts/{{ site_name }}/start.sh
    owner: "{{ site_name }}"
    group: "{{ site_name }}"
    mode: '0500'
  become: true

- name: Add templated script start_api.sh
  ansible.builtin.template:
    src: ../files/start.sh
    dest: /scripts/{{ site_name }}/start.sh
    owner: "{{ site_name }}"
    group: "{{ site_name }}"
    mode: '0500'
  become: true

- name: Add templated script mysql.sh
  ansible.builtin.template:
    src: ../files/start.sh
    dest: /scripts/{{ site_name }}/mysql.sh
    mode: '0500'
  become: true