name: Check PR

on:
  pull_request:
    branches:
      - main

env:
  SECRETS_DEV: ${{ secrets.DEV }}
  SECRETS_PROD: ${{ secrets.PROD }}
  AUTH_GCLOUD: "1"
  IS_CI: "1"
  SCRIPT_PATH: "main/ci/scripts"
  REPO_PATH: "pr"
  REPO_NAME: "site-tecktip"

jobs:
  build:
    name: Check Ansible changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: pr
      - name: Prepare to run Ansible
        run: . main/ci/scripts/prep.sh
      - name: Check Ansible playbook (DEV)
        run: . main/ci/scripts/ansible-check.sh DEV
      - name: Check Ansible playbook (PROD)
        run: . main/ci/scripts/ansible-check.sh PROD